/**
 * You are given two strings s and t.
String t is generated by random shuffling string s 
and then add one more letter at a random position.
Return the letter that was added to t.
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let sHolder = {}, tHolder={};
    for(let i=0;i<s.length;i++){
        if(sHolder[s[i]]===undefined)
            sHolder[s[i]] = 1;
        else
            sHolder[s[i]]++;
    }
    
    for(let i=0;i<t.length;i++){
        if(tHolder[t[i]]===undefined)
            tHolder[t[i]] = 1;
        else
            tHolder[t[i]]++;
    }
    for(let prop in tHolder) {
        if(sHolder[prop] ===undefined) return prop;
        if(sHolder[prop] !==tHolder[prop]) return prop;
    } 
};